---
# This playbook contains common plays that will be run on all nodes.

- name: Install zsh
  become: yes
  apt:
    name: zsh
    state: present

- name: mkdir work direcrory
  file:
    path: $HOME/documents/git
    state: directory

- name: git clone dotfiles
  ansible.builtin.git:
    repo: git@github.com:mirko-san/dotfiles.git
    dest: $HOME/documents/git/dotfiles

- name: chsh
  become: yes
  command: chsh -s /bin/zsh

- name: symlink a .gitconfig
  ansible.builtin.file:
    src: $HOME/documents/git/dotfiles/.gitconfig
    dest: $HOME/.gitconfig
    state: link

- name: symlink a .zshrc
  ansible.builtin.file:
    src: $HOME/documents/git/dotfiles/.zshrc
    dest: $HOME/.zshrc
    state: link

- name: symlink a .tmux.conf
  ansible.builtin.file:
    src: $HOME/documents/git/dotfiles/.tmux.conf
    dest: $HOME/.tmux.conf
    state: link

- name: symlink a .vimrc
  ansible.builtin.file:
    src: $HOME/documents/git/dotfiles/.vimrc
    dest: $HOME/.vimrc
    state: link

- name: create temporary build directory
  ansible.builtin.tempfile:
    state: directory
    suffix: zplug
  register: zplug_tempdir

- name: download zpulg installer
  get_url:
    url: https://raw.githubusercontent.com/zplug/installer/master/installer.zsh
    dest: '{{ zplug_tempdir.path }}/installer.zsh'

- name: install zpulg
  ignore_errors: yes
  shell: cat '{{ zplug_tempdir.path }}/installer.zsh'

- name: add ppa git
  become: yes
  apt_repository:
    repo: ppa:git-core/ppa

# git のデフォルトブランチを main にするために 2.28.0 以上にする
- name: update git
  become: yes
  apt:
    name: git=1:2.35.3-0ppa1~ubuntu20.04.1
    state: fixed
    update_cache: yes
